
import asyncio
import os

from cappo_backend.security.biscuit import extract_authority_context


async def run():
    try:
        ctx = extract_authority_context("EugGCv0FCgZpc3N1ZXIKBnZla2xvbQoOcG9saWN5X3ZlcnNpb24KFGRlbGVnYXRpb25fZGVwdGhfbWF4CgdzdWJqZWN0ChRzcGlmZmU6Ly90ZXN0L2NhbGxlcgoMZXhlY3V0aW9uX2lkCg10ZXN0X2V4ZWNfMTIzCg1jYXBhYmlsaXR5X2lkCgdjYXBfMTIzChByZXZvY2F0aW9uX3Njb3BlCgl3b3Jrc3BhY2UKEHJldm9jYXRpb25fZXBvY2gKEGFsbG93ZWRfZXhlY3V0b3IKFnNwaWZmZTovL3Rlc3QvZXhlY3V0b3IKDmFsbG93ZWRfYWN0aW9uCgtyZWNvcmQucmVhZAoMcmVjb3JkLndyaXRlCglpc3N1ZWRfYXQKFDIwMjYtMDktMDFUMTc6MzU6MjBaCgpleHBpcmVzX2F0ChQyMDI2LTA5LTAxVDE4OjM1OjIwWgoPY3VycmVudF9zdWJqZWN0CgRzdWJqCgNhbnkKEGN1cnJlbnRfZXhlY3V0b3IKBGV4ZWMKDmN1cnJlbnRfYWN0aW9uCgNhY3QKA3JlcwoJdGVybWluYXRlCgAYAyIKCggIgAgSAxiBCCIJCgcIgggSAhABIgkKBwiDCBICEAEiCgoICIQIEgMYhQgiCgoICIYIEgMYhwgiCgoICIgIEgMYiQgiCgoICIoIEgMYiwgiCQoHCIwIEgIQACIKCggIjQgSAxiOCCIKCggIjwgSAxiQCCIKCggIjwgSAxiRCCIKCggIkggSAxiTCCIKCggIlAgSAxiVCDIqChgKAggbEggIlggSAwiXCBIICIQIEgMIlwgKDgoCCBsSCAiWCBIDGJgIMioKGAoCCBsSCAiZCBIDCJoIEggIjQgSAwiaCAoOCgIIGxIICI0IEgMYmAgyNAodCgIIGxINCJsIEgMInAgSAwidCBIICI8IEgMInAgKEwoCCBsSDQibCBIDGJ4IEgMYnwgyJgokCgIIGxIGCAUSAggFGhYKBAoCCAUKCAoGIOi13NQGCgQaAggCEiQIABIghKC4g3iwXTvqOBqoIN6Zl1QDdbxqThzpZBUxfJKrZWQaQG6JL4iNWaEj1RO9eWfl67S7Rcjxiyypf_Gs4LjRbQinooCTe-KQXhsFhumqu_ZD5sgNSNt1Mhm_0--6O-EtPgsiIgogng0D9NEOu0Pi0z30tw3yU4I7Fk1nw1chVpXzwU_ILUc=")
        if ctx is None:
            raise Exception("missing_cryptographic_authority")
        print("PASS|verify_biscuit_capability|NONE|AUTHORIZED")
    except Exception as e:
        print(f"FAIL|extract_authority_context|{type(e).__name__}|missing_cryptographic_authority")

asyncio.run(run())
