import biscuit_auth
from cappo_backend.security.biscuit import get_root_key_pair, AuthorizerBuilder
token_b64 = 'EpQHCqkGCgZpc3N1ZXIKBnZla2xvbQoOcG9saWN5X3ZlcnNpb24KFGRlbGVnYXRpb25fZGVwdGhfbWF4CgdzdWJqZWN0CiFzcGlmZmU6Ly92ZWtsb20ubG9jYWwvY2xpZW50L21vY2sKDGV4ZWN1dGlvbl9pZAolZXhlY18zOTA4MTFjNjUxODY0NGMxODU2YTRiYjk3NWMyOGY4OAoNY2FwYWJpbGl0eV9pZAoKc2FuZGJveEB2MQoQcmV2b2NhdGlvbl9zY29wZQovZXhlY3V0aW9uOmV4ZWNfMzkwODExYzY1MTg2NDRjMTg1NmE0YmI5NzVjMjhmODgKEHJldm9jYXRpb25fZXBvY2gKEGFsbG93ZWRfZXhlY3V0b3IKDmFsbG93ZWRfYWN0aW9uCg8vZGVtby9hbGxvd2VkLyoKCWlzc3VlZF9hdAoUMjAyNi0wOC0zMFQxNzo1MjozMVoKCmV4cGlyZXNfYXQKFDIwMjYtMDgtMzBUMTg6MDI6MzFaCg9jdXJyZW50X3N1YmplY3QKBHN1YmoKA2FueQoQY3VycmVudF9leGVjdXRvcgoEZXhlYwoOY3VycmVudF9hY3Rpb24KA2FjdAoDcmVzCgl0ZXJtaW5hdGUKABgDIgoKCAiACBIDGIEIIgkKBwiCCBICEAEiCQoHCIMIEgIQASIKCggIhAgSAxiFCCIKCggIhggSAxiHCCIKCggIiAgSAxiJCCIKCggIiggSAxiLCCIJCgcIjAgSAhAAIgoKCAiNCBIDGIUIIgoKCAiOCBIDGI8IIgoKCAiOCBIDGI8IIgoKCAiQCBIDGJEIIgoKCAiSCBIDGJMIMioKGAoCCBsSCAiUCBIDCJUIEggIhAgSAwiVCAoOCgIIGxIICJQIEgMYlggyKgoYCgIIGxIICJcIEgMImAgSCAiNCBIDCJgICg4KAggbEggIjQgSAxiWCDI0Ch0KAggbEg0ImQgSAwiaCBIDCJsIEggIjggSAwiaCAoTCgIIGxINCJkIEgMYnAgSAxidCDImCiQKAggbEgYIBRICCAUaFgoECgIIBQoICgYgt-DR1AYKBBoCCAISJAgAEiDPpExOcMq7DOOzkevsm7hTkrUm8SI_PMsIrXGlaACEwxpAhispOmCJZxt5RPMDCuEiUKVh_2E_-N4wf9K8PF94Z3Ra_ACrAtIXxRmU10HAs7ac6ROJLqjs43YAeFhWyVwTAyIiCiCvk_M9c_J0bVoOuKPpCoB1rYe9grvPw7qkswiy1b3fvA=='
kp = get_root_key_pair()
token = biscuit_auth.Biscuit.from_base64(token_b64, kp.public_key)
auth_builder = AuthorizerBuilder()
auth_builder.add_code('allow if true;')
auth = auth_builder.build(token)
try:
    auth.authorize()
except Exception as e:
    print('Auth Error:', e)
exec_id_facts = auth.query(biscuit_auth.Rule('rule() <- execution_id()'))
print('exec_id_facts:', exec_id_facts)

