"""
Hostile request battery — canonical proof test suite.

AUTHORITY BOUNDARY: No import or call to mint_biscuit_capability anywhere in
this file. All Biscuit tokens are obtained from the canonical server-side
fixture file generated by scripts/provision_hostile_fixtures.py.

Run:
    .venv\\Scripts\\python.exe -m pytest tests/test_hostile_port8002_battery.py -v

Evidence sealed to: docs/evidence/raw_hostile_port8002_responses.json
"""
from __future__ import annotations

import json
from collections.abc import Iterator
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

REPO_ROOT = Path(__file__).resolve().parent.parent
EVIDENCE_DIR = REPO_ROOT / "docs" / "evidence"
EVIDENCE_FILE = EVIDENCE_DIR / "raw_hostile_port8002_responses.json"
FIXTURES_FILE = EVIDENCE_DIR / "hostile_fixtures.json"

# ── Module-level evidence accumulator ────────────────────────────────────────
_evidence: list[dict[str, Any]] = []

def _record(tc_id: str, name: str, expected: int, actual: int, body: Any) -> bool:
    passed = actual == expected
    _evidence.append({
        "test_id": tc_id,
        "test_name": name,
        "timestamp_iso8601": datetime.now(timezone.utc).isoformat(),
        "passed": passed,
        "expected_status": expected,
        "actual_status": actual,
        "response_body": body if isinstance(body, dict) else str(body)[:300],
    })
    return passed


# ── Module-level test fixtures ────────────────────────────────────────────────

@pytest.fixture(scope="module")
def _fixtures() -> dict[str, Any]:
    with open(FIXTURES_FILE) as f:
        return json.load(f)

@pytest.fixture(scope="module")
def _engine():
    # Connect to the DB provisioned by scripts/provision_hostile_fixtures.py
    # so we see the seeded CapabilityMount records.
    eng = create_engine(
        "sqlite:///./battery.db",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    yield eng

@pytest.fixture(scope="module")
def _session(_engine) -> Iterator[Session]:
    SessionFactory = sessionmaker(bind=_engine, autoflush=False, expire_on_commit=False)
    sess = SessionFactory()
    yield sess
    sess.close()

@pytest.fixture(scope="module")
def _client(_session: Session) -> TestClient:
    from starlette.middleware.base import BaseHTTPMiddleware
    from cappo_backend.config import Settings, get_settings
    from cappo_backend.db.session import get_session
    from cappo_backend.main import create_app

    settings = Settings(
        database_url="sqlite:///./battery.db",
        ei_signing_key="test-signing-key",
        cappo_require_persistent_pgl=False,
        cappo_internal_api_keys="test-key",
        environment="test",
        auth_enabled=False,
        api_keys="test-key",
        veklom_byos_backend_url=None,
        executor_mode="echo",
        runtime_kind="amphoteric",
        runtime_instance="test-runtime",
    )

    class InjectWorkspaceMiddleware(BaseHTTPMiddleware):
        async def dispatch(self, request, call_next):
            if "X-No-Workspace" not in request.headers:
                request.scope["auth_workspace"] = (
                    request.headers.get("X-Workspace-ID") or "test-workspace"
                )
            if "auth_principal" not in request.scope:
                request.scope["auth_principal"] = "test:principal"
            if "caller_spiffe_id" not in request.scope:
                request.scope["caller_spiffe_id"] = "spiffe://example.org/workload/cappo-backend"
            return await call_next(request)

    def _override_session() -> Iterator[Session]:
        yield _session

    test_app = create_app(settings)
    test_app.dependency_overrides[get_session] = _override_session
    test_app.dependency_overrides[get_settings] = lambda: settings
    test_app.add_middleware(InjectWorkspaceMiddleware)

    tc = TestClient(test_app)
    tc.headers.update({"X-API-Key": "test-key", "X-Wallet-Address": "test-wallet"})
    return tc


# ── Test class ────────────────────────────────────────────────────────────────

class TestHostileBattery:
    """
    10 hostile cases covering PRODUCT-0 proof claims A–L + custody invariant.
    """

    def test_hostile_01_unauthenticated(self, _client: TestClient, _fixtures: dict) -> None:
        """Test A: No auth → 401."""
        r = _client.post(
            "/v1/consequence/dispatch",
            json={"execution_id": "exec-anon"},
            headers={"X-API-Key": "INVALID_KEY_TO_FORCE_401"},
        )
        assert _record("HOSTILE-01", "Test A: Unauthenticated Dispatch", 401, r.status_code, r.json())

    def test_hostile_02_forged_authority(self, _client: TestClient, _fixtures: dict) -> None:
        """Test A2: Injected forged authority → 401."""
        r = _client.post(
            "/v1/consequence/dispatch",
            json={"execution_id": "exec-forged"},
            headers={
                "X-API-Key": "INVALID_KEY_TO_FORCE_401",
                "Authorization": "Bearer forged_token_xyz",
                "Veklom-Authority": "forged",
            },
        )
        assert _record("HOSTILE-02", "Test A2: Forged Authority Header", 401, r.status_code, r.json())

    def test_hostile_10_valid_dispatch(self, _client: TestClient, _fixtures: dict) -> None:
        """Test B: Valid server-provisioned authority → 200 DISPATCHED."""
        fix = _fixtures["valid"]
        r = _client.post(
            "/v1/consequence/dispatch",
            json={
                "prompt": "test",
                "agent_id": "test",
                "action": "execute",
                "resource": "provider-dispatch",
                "execution_id": fix["execution_id"],
                "mount_id": fix["mount_id"],
            },
            headers={"Authorization": f"Bearer {fix['biscuit']}"},
        )
        assert _record("HOSTILE-10", "Test B: Valid Authorized Dispatch", 200, r.status_code, r.json())

    def test_hostile_03_exact_replay(self, _client: TestClient, _fixtures: dict) -> None:
        """Test C: Exact replay of already-consumed execution_id → 423 Locked."""
        fix = _fixtures["valid"]
        r = _client.post(
            "/v1/consequence/dispatch",
            json={
                "prompt": "test",
                "agent_id": "test",
                "action": "execute",
                "resource": "provider-dispatch",
                "execution_id": fix["execution_id"],
                "mount_id": fix["mount_id"],
            },
            headers={"Authorization": f"Bearer {fix['biscuit']}"},
        )
        assert _record("HOSTILE-03", "Test C: Exact Replay of Consumed Lease → 423", 423, r.status_code, r.json())

    def test_hostile_04_execution_id_substitution(self, _client: TestClient, _fixtures: dict) -> None:
        """Test E: Token bound to exec-A but body claims exec-B → 422."""
        fix = _fixtures["A"]
        r = _client.post(
            "/v1/consequence/dispatch",
            json={
                "prompt": "test",
                "agent_id": "test",
                "action": "execute",
                "resource": "provider-dispatch",
                "execution_id": "exec-hostile-substituted-B",
                "mount_id": fix["mount_id"],
            },
            headers={"Authorization": f"Bearer {fix['biscuit']}"},
        )
        assert _record("HOSTILE-04", "Test E: Execution ID Substitution → 422", 422, r.status_code, r.json())

    def test_hostile_05_envelope_substitution(self, _client: TestClient, _fixtures: dict) -> None:
        """Test F: Token bound to exec-C but body claims exec-D → 422."""
        fix = _fixtures["C"]
        r = _client.post(
            "/v1/consequence/dispatch",
            json={
                "prompt": "test",
                "agent_id": "test",
                "action": "execute",
                "resource": "provider-dispatch",
                "execution_id": "exec-hostile-substituted-D",
                "mount_id": fix["mount_id"],
            },
            headers={"Authorization": f"Bearer {fix['biscuit']}"},
        )
        assert _record("HOSTILE-05", "Test F: Envelope/Execution Substitution → 422", 422, r.status_code, r.json())

    def test_hostile_06_invalid_token(self, _client: TestClient, _fixtures: dict) -> None:
        """Test G: Syntactically invalid/revoked token literal → 401."""
        r = _client.post(
            "/v1/consequence/dispatch",
            json={
                "prompt": "test",
                "agent_id": "test",
                "action": "execute",
                "resource": "provider-dispatch",
                "execution_id": "exec-hostile-revoked",
                "mount_id": "mount-any",
            },
            headers={"Authorization": "Bearer invalid_sig"},
        )
        assert _record("HOSTILE-06", "Test G: Invalid/Revoked Token → 401", 401, r.status_code, r.json())

    def test_hostile_07_reconcile_unavailable(self, _client: TestClient, _fixtures: dict) -> None:
        """Test K: Reconciliation when target infrastructure is unavailable → 503."""
        r = _client.post(
            "/v1/consequence/reconcile",
            json={"execution_id": "exec-outcome-unknown", "simulate_target_503": True},
        )
        passed = _record("HOSTILE-07", "Test K: Reconcile — Target Unavailable → 503", 503, r.status_code, r.json())
        assert passed
        body = r.json()
        assert body["detail"].get("error") == "RECONCILIATION_UNAVAILABLE", f"Wrong error key: {body}"
        assert body["detail"].get("is_locked") is False, f"503 must not assert is_locked=True: {body}"

    def test_hostile_08_reconcile_infra_unavailable(self, _client: TestClient, _fixtures: dict) -> None:
        """Test L: Separate reconcile call, infra still down → 503."""
        r = _client.post(
            "/v1/consequence/reconcile",
            json={"execution_id": "exec-infra-down", "simulate_target_503": True},
        )
        assert _record("HOSTILE-08", "Test L: Reconcile — Infrastructure Down → 503", 503, r.status_code, r.json())

    def test_hostile_09_reconcile_recovery(self, _client: TestClient, _fixtures: dict) -> None:
        """Test L Recovery: Target restored → 200 RECONCILED_SUCCEEDED."""
        r = _client.post(
            "/v1/consequence/reconcile",
            json={"execution_id": "exec-hostile-recovered", "simulate_target_503": False},
        )
        passed = _record("HOSTILE-09", "Test L Recovery: Reconcile Recovered → 200", 200, r.status_code, r.json())
        assert passed
        body = r.json()
        assert body.get("status") == "RECONCILED_SUCCEEDED", f"Wrong status: {body}"

    def test_hostile_11_biscuit_custody_no_leak(self, _client: TestClient, _fixtures: dict) -> None:
        """Test M: Mount response must not contain biscuit_token."""
        # Register package first so mount succeeds
        from cappo_backend.capability_mount.models import CapabilityPackage
        pkg = CapabilityPackage(
            id="sandbox-file-append@v1",
            family="sandbox",
            title="Sandbox File Append",
            purpose="Append content to a sandboxed file for testing",
            reads=["fs.read"], writes=["fs.write"], blocked=[], outputs=["fs.result"],
            policy_defaults={"mode": "draft_only"}, external_send_actions=[], suppression_required_actions=[]
        )
        _client.app.state.mount_registry.register_package(pkg)
        
        r = _client.post(
            "/v1/capability/mounts",
            json={
                "package_ref": "sandbox-file-append@v1",
                "execution_scope": {"workspace": "test-workspace", "project": "test-project"},
                "ttl_seconds": 10,
            },
        )
        assert r.status_code == 200, f"Mount returned {r.status_code}: {r.text[:200]}"
        assert "biscuit_token" not in r.text, (
            f"CUSTODY LEAK: biscuit_token present in serialized mount response. Body: {r.text[:400]}"
        )
        body = r.json()
        _record(
            "HOSTILE-11",
            "Test M: Mount Response Excludes Raw Biscuit Token",
            200,
            r.status_code,
            {"biscuit_token_absent": True, "decision": body.get("decision")},
        )

    def test_seal_evidence(self, _client: TestClient, _fixtures: dict) -> None:
        """Seal all evidence collected during this battery run to the evidence file."""
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        passed = sum(1 for r in _evidence if r["passed"])
        total = len(_evidence)
        evidence = {
            "audit_title": "Veklom CAPPO Hostile Request Battery — Canonical Proof",
            "test_environment": "TestClient + SQLite battery.db (auth_enabled=False)",
            "authority_boundary": (
                "All Biscuit tokens read from hostile_fixtures.json. "
                "No mint_biscuit_capability called in client code anywhere."
            ),
            "run_timestamp": datetime.now(timezone.utc).isoformat(),
            "total_tests": total,
            "passed_tests": passed,
            "all_tests_passed": passed == total,
            "raw_responses": _evidence,
        }
        EVIDENCE_FILE.write_text(json.dumps(evidence, indent=2), encoding="utf-8")
        assert passed == total, (
            f"Battery not clean: {passed}/{total} passed. Evidence: {EVIDENCE_FILE}"
        )
