"""CAPPO runtime FastAPI application.

Middleware stack order, outermost → innermost:
    1. RequestLogging
    2. CORS
    3. Amphoteric sensing
    4. Auth
    5. Ollama lifecycle policy signal

Budget / kill-switch and EI / LAW 0 remain enforced inside the governed
execution pipeline. There is no public bypass for ``/v1/exec``.

Synthetic/random VNP measurements are deliberately absent. VNP trust/evidence
must be derived from attributable external probe telemetry, never generated by
this application process.
"""

import asyncio
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from cappo_backend.api.routers.admin_router import router as admin_router
from cappo_backend.api.routers.agents_router import router as agents_router
from cappo_backend.api.routers.audit_router import router as audit_router
from cappo_backend.api.routers.authorization_router import router as authorization_router
from cappo_backend.api.routers.benchmarks_router import router as benchmarks_router
from cappo_backend.api.routers.capability_beacon_router import issuer_key_router
from cappo_backend.api.routers.capability_beacon_router import router as capability_beacon_router
from cappo_backend.api.routers.capability_mount_router import router as capability_mount_router
from cappo_backend.api.routers.exec_router import router as exec_router
from cappo_backend.api.routers.governance_v2_router import router as governance_v2_router
from cappo_backend.api.routers.gpc_router import router as gpc_router
from cappo_backend.api.routers.health_router import router as health_router
from cappo_backend.api.routers.interlink import router as interlink_router
from cappo_backend.api.routers.interlink_vnp import router as interlink_vnp_router
from cappo_backend.api.routers.license_router import router as license_router
from cappo_backend.api.routers.platform_router import router as platform_router
from cappo_backend.api.routers.protocol_router import router as protocol_router
from cappo_backend.api.routers.vnp_control_plane_router import router as vnp_admin_router
from cappo_backend.api.routers.vnp_router import router as vnp_router
from cappo_backend.api.routers.wid_probe_router import router as wid_probe_router
from cappo_backend.api.routers.x402_router import api_x402_router, root_discovery_router
from cappo_backend.capability_mount.service import MountRegistry, load_packages_from_json
from cappo_backend.config import Settings, get_settings
from cappo_backend.core.security.ollama_sanitizer import OllamaBleedSanitizerMiddleware
from cappo_backend.observability.logging import configure_logging
from cappo_backend.observability.middleware import RequestLoggingMiddleware
from cappo_backend.security.amphoteric_middleware import AmphotericSensingMiddleware
from cappo_backend.security.auth_middleware import AuthMiddleware
from cappo_backend.security.spiffe_middleware import SVIDEnforcementMiddleware


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    settings = getattr(app.state, "settings", None) or get_settings()
    configure_logging(settings.log_level)
    settings.validate_production()

    from cappo_backend.services.capi_registration import maintain_capi_registration

    capi_stop = asyncio.Event()
    capi_task = asyncio.create_task(maintain_capi_registration(settings, capi_stop))
    try:
        yield
    finally:
        capi_stop.set()
        if not capi_task.done():
            capi_task.cancel()
        try:
            await capi_task
        except asyncio.CancelledError:
            pass


def create_app(settings: Settings | None = None) -> FastAPI:
    """Build the FastAPI app. Accept explicit settings for testability."""
    settings = settings or get_settings()

    app = FastAPI(title="CAPPO Runtime", version="0.1.0", lifespan=lifespan)
    app.state.settings = settings
    
    if settings.redis_url:
        import redis
        app.state.redis_client = redis.Redis.from_url(
            settings.redis_url,
            socket_timeout=2.0,
            socket_connect_timeout=2.0,
            decode_responses=True
        )
    else:
        app.state.redis_client = None

    mount_registry = MountRegistry()
    for package in load_packages_from_json(settings.capability_packages_json):
        mount_registry.register_package(package)
    app.state.mount_registry = mount_registry

    from cappo_backend.services.x402_payment import X402FreemiumASGI, get_x402_manager

    x402_manager = get_x402_manager(settings)
    if x402_manager.is_enabled:
        x402_routes = x402_manager.routes
        if settings.auth_enabled and settings.api_key_set:
            x402_routes = {
                route: config
                for route, config in x402_manager.routes.items()
                if route != "POST /v1/exec"
            }
        app.add_middleware(
            X402FreemiumASGI,
            server=x402_manager.server,
            routes=x402_routes,
            settings=settings,
        )

    app.add_middleware(OllamaBleedSanitizerMiddleware)
    app.add_middleware(SVIDEnforcementMiddleware, settings=settings)
    app.add_middleware(AuthMiddleware, settings=settings)
    app.add_middleware(AmphotericSensingMiddleware)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origin_list,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*", "X-Wallet-Address", "X-Payment", "X-Workspace-ID"],
        expose_headers=[
            "X-Request-ID",
            "X-402-Version",
            "X-402-Chain",
            "X-402-Recipient",
            "X-402-Token",
            "X-402-Amount",
            "X-402-Resource",
            "X-402-App-Id",
        ],
    )
    app.add_middleware(RequestLoggingMiddleware)

    from cappo_backend.adapters.legacy.router import router as legacy_adapter_router

    app.include_router(vnp_router)
    app.include_router(vnp_admin_router)
    app.include_router(agents_router)
    app.include_router(authorization_router)
    app.include_router(exec_router)
    app.include_router(health_router)
    app.include_router(wid_probe_router)
    app.include_router(admin_router)
    app.include_router(audit_router)
    app.include_router(governance_v2_router)
    app.include_router(license_router)
    app.include_router(legacy_adapter_router)
    app.include_router(interlink_router, prefix="/api/interlink")
    app.include_router(
        interlink_vnp_router,
        prefix="/api/internal/interlink/vnp",
        tags=["interlink_vnp"],
    )
    app.include_router(platform_router)
    app.include_router(benchmarks_router)
    app.include_router(capability_mount_router)
    app.include_router(capability_beacon_router)
    app.include_router(issuer_key_router)
    app.include_router(gpc_router)
    app.include_router(api_x402_router, prefix="/api")
    app.include_router(root_discovery_router)
    app.include_router(protocol_router)

    from fastapi import Request
    from fastapi.responses import JSONResponse

    @app.exception_handler(Exception)
    async def global_exception_handler(request: Request, exc: Exception):
        return JSONResponse(
            status_code=500,
            content={
                "error": "INTERNAL_SERVER_ERROR",
                "detail": "An unexpected error occurred. Stack trace is hidden for security.",
            },
        )

    return app


app = create_app()
