"""Compile a blueprint pipeline graph into governed Python.

Ordering and parallel levels follow the original GPC compiler (Kahn's algorithm).
The difference is what each step becomes: not a direct call, but a governed one.
Every step gets its own narrowly scoped CAPPO mount, asks CAPPO for a decision,
runs the caller's effect only on ALLOW, and terminates the mount in ``finally``.
Blocked steps are asked anyway, so the denial is recorded as evidence. Steps no
capability covers raise instead of running. The generated code holds no
authority of its own; it carries only the operator's session token at run time.
"""

from __future__ import annotations

import ast
import hashlib
import json
import re
from typing import Any

GOVERNED_KINDS = {"read", "write", "blocked"}
SKIPPED_KINDS = {"intent", "mount"}  # structural nodes: no code of their own


class PipelineCycleError(ValueError):
    pass


def _ident(value: str, used: set[str]) -> str:
    base = re.sub(r"[^0-9a-zA-Z_]", "_", value).strip("_").lower() or "step"
    if base[0].isdigit():
        base = f"step_{base}"
    name, n = base, 2
    while name in used:
        name, n = f"{base}_{n}", n + 1
    used.add(name)
    return name


def _order(node_ids: list[str], edges: list[tuple[str, str]]) -> tuple[list[str], list[list[str]]]:
    in_degree = {nid: 0 for nid in node_ids}
    adjacency: dict[str, list[str]] = {nid: [] for nid in node_ids}
    for source, target in edges:
        if source in adjacency and target in in_degree:
            adjacency[source].append(target)
            in_degree[target] += 1
    levels: list[list[str]] = []
    current = [nid for nid in node_ids if in_degree[nid] == 0]
    seen = 0
    while current:
        levels.append(current)
        seen += len(current)
        nxt: list[str] = []
        for nid in current:
            for downstream in adjacency[nid]:
                in_degree[downstream] -= 1
                if in_degree[downstream] == 0:
                    nxt.append(downstream)
        current = nxt
    if seen != len(node_ids):
        raise PipelineCycleError(f"pipeline contains a cycle ({seen}/{len(node_ids)} steps orderable)")
    return [nid for level in levels for nid in level], levels


_PRELUDE = '''"""Governed pipeline generated by the Veklom Blueprint compiler.

Every step runs under its own CAPPO mount: mount -> ask -> act only on ALLOW ->
terminate. This file holds no authority; it uses your session at run time.

    VEKLOM_URL=https://veklom.com VEKLOM_TOKEN=<session> VEKLOM_WORKSPACE=<id> python pipeline.py
"""
import os
from concurrent.futures import ThreadPoolExecutor

import httpx

BASE = os.environ.get("VEKLOM_URL", "https://veklom.com").rstrip("/")
WORKSPACE = os.environ["VEKLOM_WORKSPACE"]
PROJECT = os.environ.get("VEKLOM_PROJECT", "sandbox")
HTTP = httpx.Client(base_url=BASE, headers={"Authorization": f"Bearer {os.environ['VEKLOM_TOKEN']}"}, timeout=30)
MOUNTS = "/api/capi/interlink/capability/mounts"


class Denied(Exception):
    pass


class Uncovered(Exception):
    pass


def governed_step(package_ref, action, kind, effect=None):
    """Mount exactly one action, ask CAPPO, run ``effect`` only on ALLOW, always terminate."""
    scope = {"reads": [action] if kind == "read" else [], "writes": [action] if kind == "write" else [],
             "blocked": [action] if kind == "blocked" else []}
    mount = HTTP.post(MOUNTS, json={"package_ref": package_ref, "role": "ephemeral_executor", "policy": {},
                                    "execution_scope": {"workspace": WORKSPACE, "project": PROJECT},
                                    "requested_action_scope": scope, "ttl_seconds": 120}).raise_for_status().json()
    if mount.get("decision") != "allow":
        raise Denied(f"mount refused for {action}: {mount.get('reason')}")
    token, mount_id = mount["token"], mount["token"]["mount_id"]
    try:
        decision = HTTP.post(f"{MOUNTS}/{mount_id}/actions", json={
            "token_id": token["token_id"], "nonce": token["nonce"], "action": action}).raise_for_status().json()
        evidence = decision.get("anchoring", {}).get("anchor_id")
        print(f"{action}: {decision['decision'].upper()} ({decision.get('reason')}) evidence={evidence}")
        if decision["decision"] != "allow":
            raise Denied(f"{action}: {decision.get('reason')}")
        return effect() if effect else decision
    finally:
        HTTP.post(f"/api/cappo/v1/capability/mounts/{mount_id}/terminate", json={"reason": "explicit_terminate"})
'''


def compile_pipeline(graph: dict[str, Any]) -> dict[str, Any]:
    nodes = {str(n["id"]): n for n in graph.get("nodes", [])}
    edges = [
        (str(e.get("source_node_id", e.get("from"))), str(e.get("target_node_id", e.get("to"))))
        for e in graph.get("edges", [])
    ]
    warnings: list[str] = []
    try:
        execution_order, levels = _order(list(nodes), edges)
    except PipelineCycleError as exc:
        return {"success": False, "python_code": "", "node_count": len(nodes), "execution_order": [],
                "parallel_levels": [], "warnings": [str(exc)]}

    used: set[str] = {"main", "governed_step", "Denied", "Uncovered", "HTTP", "BASE", "WORKSPACE", "PROJECT", "MOUNTS"}
    names: dict[str, str] = {}
    functions: list[str] = []
    for nid in execution_order:
        node = nodes[nid]
        kind = str(node.get("node_type") or node.get("type") or "")
        if kind in SKIPPED_KINDS:
            continue
        config = node.get("config") or {}
        name = names[nid] = _ident(f"step_{nid}", used)
        label = str(node.get("label") or config.get("clause") or nid)
        doc = json.dumps(label)
        if kind in GOVERNED_KINDS and config.get("package_ref") and config.get("action"):
            note = "  # CAPPO blocks this action; asking records the denial as evidence." if kind == "blocked" else ""
            functions.append(
                f"def {name}(effect=None):\n    {doc}\n"
                f"    return governed_step({json.dumps(config['package_ref'])}, {json.dumps(config['action'])}, "
                f"{json.dumps(kind)}, effect){note}\n"
            )
            if kind == "blocked":
                warnings.append(f"{nid}: {config['action']} is blocked by {config['package_ref']}; the pipeline will stop here")
        else:
            functions.append(
                f"def {name}(effect=None):\n    {doc}\n"
                f"    raise Uncovered({json.dumps(f'no capability covers this step: {label}')})\n"
            )
            warnings.append(f"{nid}: no capability covers this step; add one before running")

    body: list[str] = []
    for level in levels:
        level_names = [names[nid] for nid in level if nid in names]
        if not level_names:
            continue
        if len(level_names) == 1:
            body.append(f"    {level_names[0]}()")
        else:
            calls = ", ".join(f"pool.submit({n})" for n in level_names)
            body.append(f"    with ThreadPoolExecutor() as pool:  # independent steps run in parallel\n"
                        f"        for future in [{calls}]:\n            future.result()")
    main = "def main():\n" + ("\n".join(body) if body else "    pass") + "\n"
    code = _PRELUDE + "\n\n" + "\n\n".join(functions) + ("\n\n" if functions else "") + main + \
        "\n\nif __name__ == \"__main__\":\n    main()\n"
    ast.parse(code)  # never hand back code that does not parse
    return {
        "success": True,
        "python_code": code,
        "code_hash": "sha256:" + hashlib.sha256(code.encode()).hexdigest(),
        "node_count": len(nodes),
        "execution_order": execution_order,
        "parallel_levels": levels,
        "warnings": warnings,
    }


def blueprint_to_pipeline(plan: dict[str, Any]) -> dict[str, Any]:
    """The canvas graph for a compiled blueprint (GPC node/edge shape, laid out left to right)."""
    steps = {s["id"]: s for s in plan.get("steps", [])}
    nodes, edges = [], []
    for column, node in enumerate(plan["graph"]["nodes"]):
        step = steps.get(node["id"], {})
        config = {k: step[k] for k in ("action", "package_ref", "clause", "reason") if step.get(k)}
        if node["type"] == "mount":
            config["package_ref"] = node["id"].removeprefix("mount:")
        nodes.append({"id": node["id"], "node_type": node["type"], "label": node.get("description") or node["id"],
                      "config": config, "position": {"x": 40 + column * 280, "y": 80}})
    for i, edge in enumerate(plan["graph"]["edges"]):
        edges.append({"id": f"e{i}", "source_node_id": edge["from"], "source_port_id": "out",
                      "target_node_id": edge["to"], "target_port_id": "in"})
    return {"pipeline_id": plan["id"], "tenant_id": "", "name": plan.get("name"), "nodes": nodes, "edges": edges}
