"""add_merkle_leaf_sequence_table

Revision ID: 00e31b0a5c20
Revises: 4d067f8117ac
Create Date: 2026-08-26 15:02:06.302587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_merkle_leaf_sequence_table

Revision ID: 00e31b0a5c20
Revises: 4d067f8117ac
Create Date: 2026-08-26 15:02:06.302587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e31b0a5c20'
down_revision: Union[str, None] = '4d067f8117ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merkle_leaf_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed the singleton row. This is the ONE legitimate initialization.
    # If this row ever disappears in production, assign_merkle_leaf_index()
    # will raise RuntimeError rather than silently reinitializing,
    # preventing index reuse on a live database.
    op.execute(
        "INSERT INTO merkle_leaf_sequence (id, next_value) VALUES (1, 0)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merkle_leaf_sequence')
    # ### end Alembic commands ###
