"""add_kms_key_records

Revision ID: 0855d6ec422d
Revises: 339178922860
Create Date: 2026-08-28 19:54:47.890417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0855d6ec422d'
down_revision: Union[str, None] = '339178922860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kms_key_records',
    sa.Column('kid', sa.String(), nullable=False),
    sa.Column('public_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('private_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETIRED', 'REVOKED', name='kmskeystatus'), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('kid')
    )
    with op.batch_alter_table('kms_key_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kms_key_records_kid'), ['kid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kms_key_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kms_key_records_kid'))

    op.drop_table('kms_key_records')
    # ### end Alembic commands ###
