"""Add CapabilityActionReceipt table

Revision ID: 0a392376cb62
Revises: 9978153219c2
Create Date: 2026-08-26 12:29:47.257365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a392376cb62'
down_revision: Union[str, None] = '9978153219c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_action_receipts',
    sa.Column('receipt_id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('mount_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('principal', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('pgl_anchor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_mount_id'), ['mount_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_principal'), ['principal'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_token_id'), ['token_id'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('vnp_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('did', sa.String(length=100), nullable=False),
    sa.Column('commercial_profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did')
    )
    op.create_table('vnp_route_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('recommendations_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='Guest Developer', nullable=False),
    sa.Column('tenant_name', sa.String(length=100), server_default='Global Public Tenant', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vnp_validators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('did', sa.String(length=100), nullable=False),
    sa.Column('stake_amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did')
    )
    op.create_table('document_indexes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_doc_id', sa.String(), nullable=True),
    sa.Column('index_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_indexes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_indexes_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_indexes_provider_doc_id'), ['provider_doc_id'], unique=False)

    op.create_table('retrieval_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('tool_used', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retrieval_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieval_sessions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_sessions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('vnp_api_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('api_did', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('x402_compliant', sa.Boolean(), nullable=False),
    sa.Column('stability_rating', sa.String(length=50), nullable=False),
    sa.Column('last_measured', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['vnp_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_did')
    )
    with op.batch_alter_table('vnp_api_state', schema=None) as batch_op:
        batch_op.create_index('idx_api_state_composite', [sa.literal_column('composite_score DESC')], unique=False)

    op.create_table('vnp_compliance_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_name', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=255), nullable=False),
    sa.Column('affected_entity', sa.String(length=255), nullable=False),
    sa.Column('hash_payload', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['vnp_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_sdk_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('policy_entitlements', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('retrieval_traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('page_refs', sa.JSON(), nullable=True),
    sa.Column('section_refs', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retrieval_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieval_traces_session_id'), ['session_id'], unique=False)

    op.create_table('vnp_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_api_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_performance_leaderboard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_composite_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rank_index', sa.Integer(), nullable=False),
    sa.Column('telemetry_samples_count', sa.Integer(), nullable=False),
    sa.Column('best_performing_region', sa.String(length=50), nullable=True),
    sa.Column('is_active_champion', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_api_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id')
    )
    with op.batch_alter_table('vnp_performance_leaderboard', schema=None) as batch_op:
        batch_op.create_index('idx_leaderboard_score_rank', [sa.literal_column('monthly_composite_score DESC'), sa.literal_column('rank_index ASC')], unique=False)

    op.create_table('vnp_probe_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_api_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_regional_telemetry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('uptime_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('throughput_rps', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_api_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vnp_regional_telemetry', schema=None) as batch_op:
        batch_op.create_index('idx_telemetry_measured', [sa.literal_column('measured_at DESC')], unique=False)

    op.create_table('vnp_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_user_id', sa.Uuid(), nullable=True),
    sa.Column('target_api_id', sa.Uuid(), nullable=False),
    sa.Column('microtransaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('gas_fee_usd', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['vnp_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_api_id'], ['vnp_api_state.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microtransaction_id')
    )
    with op.batch_alter_table('vnp_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_micro', ['microtransaction_id'], unique=False)

    with op.batch_alter_table('governed_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_mode', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('governed_runs', schema=None) as batch_op:
        batch_op.drop_column('execution_mode')

    with op.batch_alter_table('vnp_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_micro')

    op.drop_table('vnp_transactions')
    with op.batch_alter_table('vnp_regional_telemetry', schema=None) as batch_op:
        batch_op.drop_index('idx_telemetry_measured')

    op.drop_table('vnp_regional_telemetry')
    op.drop_table('vnp_probe_events')
    with op.batch_alter_table('vnp_performance_leaderboard', schema=None) as batch_op:
        batch_op.drop_index('idx_leaderboard_score_rank')

    op.drop_table('vnp_performance_leaderboard')
    op.drop_table('vnp_incidents')
    with op.batch_alter_table('retrieval_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieval_traces_session_id'))

    op.drop_table('retrieval_traces')
    op.drop_table('vnp_sdk_credentials')
    op.drop_table('vnp_compliance_audit_log')
    with op.batch_alter_table('vnp_api_state', schema=None) as batch_op:
        batch_op.drop_index('idx_api_state_composite')

    op.drop_table('vnp_api_state')
    with op.batch_alter_table('retrieval_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieval_sessions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_sessions_agent_id'))

    op.drop_table('retrieval_sessions')
    with op.batch_alter_table('document_indexes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_indexes_provider_doc_id'))
        batch_op.drop_index(batch_op.f('ix_document_indexes_document_id'))

    op.drop_table('document_indexes')
    op.drop_table('vnp_validators')
    op.drop_table('vnp_users')
    op.drop_table('vnp_route_snapshots')
    op.drop_table('vnp_providers')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_workspace_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_token_id'))
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_principal'))
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_mount_id'))
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_execution_id'))

    op.drop_table('capability_action_receipts')
    # ### end Alembic commands ###
