"""Add SPIFFE fields to capability_action_receipt

Revision ID: 14044ffdf26d
Revises: 0a392376cb62
Create Date: 2026-08-26 13:13:11.794526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14044ffdf26d'
down_revision: Union[str, None] = '0a392376cb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caller_spiffe_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('executor_spiffe_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('caller_cert_sha256', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('trust_domain', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('svid_not_before', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('svid_not_after', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('policy_version', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.drop_column('policy_version')
        batch_op.drop_column('svid_not_after')
        batch_op.drop_column('svid_not_before')
        batch_op.drop_column('trust_domain')
        batch_op.drop_column('caller_cert_sha256')
        batch_op.drop_column('executor_spiffe_id')
        batch_op.drop_column('caller_spiffe_id')
    # ### end Alembic commands ###
