"""n8n execution registry

Revision ID: 339178922860
Revises: 34a9e8335e0f
Create Date: 2026-08-28 19:38:32.170865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339178922860'
down_revision: Union[str, None] = '34a9e8335e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consequence_execution_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('intent_hash', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.String(), nullable=True),
    sa.Column('mount_id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('principal', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completion_proof_type', sa.String(), nullable=True),
    sa.Column('completion_proof_ref', sa.String(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('proof_subject_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('operation_id', 'version', name='uq_consequence_event_op_version')
    )
    with op.batch_alter_table('consequence_execution_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consequence_execution_events_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consequence_execution_events_intent_hash'), ['intent_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_consequence_execution_events_mount_id'), ['mount_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consequence_execution_events_operation_id'), ['operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consequence_execution_events_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consequence_execution_events_state'), ['state'], unique=False)

    op.create_table('execution_registry',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('action_hash', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('execution_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_registry_jti'), ['jti'], unique=True)

    op.create_table('lease_states',
    sa.Column('lease_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lease_id')
    )
    op.create_table('p5_operations',
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('consequence_id', sa.String(), nullable=False),
    sa.Column('sink_class', sa.String(), nullable=False),
    sa.Column('current_truth_state', sa.String(), nullable=False),
    sa.Column('intent_hash', sa.String(), nullable=False),
    sa.Column('actor_identity', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('operation_id')
    )
    with op.batch_alter_table('p5_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_p5_operations_consequence_id'), ['consequence_id'], unique=False)

    op.create_table('revocation_policies',
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_value', sa.String(), nullable=False),
    sa.Column('is_cancel', sa.Boolean(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scope_type', 'scope_value')
    )
    op.create_table('p5_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('event_sequence', sa.Integer(), nullable=False),
    sa.Column('previous_event_hash', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('previous_truth_state', sa.String(), nullable=True),
    sa.Column('asserted_truth_state', sa.String(), nullable=True),
    sa.Column('proof_type', sa.String(), nullable=True),
    sa.Column('proof_subject_hash', sa.String(), nullable=True),
    sa.Column('cappo_decision_id', sa.String(), nullable=True),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['p5_operations.operation_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('p5_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_p5_events_operation_id'), ['operation_id'], unique=False)

    op.create_table('p5_outbox',
    sa.Column('outbox_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['p5_events.event_id'], ),
    sa.PrimaryKeyConstraint('outbox_id')
    )
    with op.batch_alter_table('p5_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_p5_outbox_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('p5_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_p5_outbox_event_id'))

    op.drop_table('p5_outbox')
    with op.batch_alter_table('p5_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_p5_events_operation_id'))

    op.drop_table('p5_events')
    op.drop_table('revocation_policies')
    with op.batch_alter_table('p5_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_p5_operations_consequence_id'))

    op.drop_table('p5_operations')
    op.drop_table('lease_states')
    with op.batch_alter_table('execution_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_registry_jti'))

    op.drop_table('execution_registry')
    with op.batch_alter_table('consequence_execution_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consequence_execution_events_state'))
        batch_op.drop_index(batch_op.f('ix_consequence_execution_events_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_consequence_execution_events_operation_id'))
        batch_op.drop_index(batch_op.f('ix_consequence_execution_events_mount_id'))
        batch_op.drop_index(batch_op.f('ix_consequence_execution_events_intent_hash'))
        batch_op.drop_index(batch_op.f('ix_consequence_execution_events_execution_id'))

    op.drop_table('consequence_execution_events')
    # ### end Alembic commands ###
