"""add revocation_scope to capability_lease

Revision ID: 34a9e8335e0f
Revises: 39427b778a4b
Create Date: 2026-08-27 07:37:45.260979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a9e8335e0f'
down_revision: Union[str, None] = '39427b778a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revocation_scope', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_leases', schema=None) as batch_op:
        batch_op.drop_column('revocation_scope')

    # ### end Alembic commands ###
