"""add_eei_fields_to_capability_action_receipts

Revision ID: 39427b778a4b
Revises: 5eae80473601
Create Date: 2026-08-26 20:55:17.014756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39427b778a4b'
down_revision: Union[str, None] = '5eae80473601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eei_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lease_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('operator_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_eei_id'), ['eei_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_lease_id'), ['lease_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_profile_id'))
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_operator_id'))
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_lease_id'))
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_eei_id'))
        batch_op.drop_column('operator_id')
        batch_op.drop_column('lease_id')
        batch_op.drop_column('profile_id')
        batch_op.drop_column('eei_id')

    # ### end Alembic commands ###
