"""add biscuit_token_sha256

Revision ID: 3f5c8bcd93f7
Revises: 14044ffdf26d
Create Date: 2026-08-26 13:57:57.929737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5c8bcd93f7'
down_revision: Union[str, None] = '14044ffdf26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biscuit_token_sha256', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.drop_column('biscuit_token_sha256')

    # ### end Alembic commands ###
