"""add_budget_hold

Revision ID: 4a2a4824e77d
Revises: 0855d6ec422d
Create Date: 2026-08-28 20:13:11.438410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2a4824e77d'
down_revision: Union[str, None] = '0855d6ec422d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_budget_holds',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SETTLED', 'RELEASED', name='holdstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_budgets.workspace_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('workspace_budget_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_budget_holds_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_budget_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_budget_holds_workspace_id'))

    op.drop_table('workspace_budget_holds')
    # ### end Alembic commands ###
