"""add_merkle_leaf_index_to_capability_action_receipts

Revision ID: 4d067f8117ac
Revises: aca1358ae65e
Create Date: 2026-08-26 14:57:22.686465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d067f8117ac'
down_revision: Union[str, None] = 'aca1358ae65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merkle_leaf_index', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_capability_action_receipts_merkle_leaf_index'), ['merkle_leaf_index'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_action_receipts_merkle_leaf_index'))
        batch_op.drop_column('merkle_leaf_index')

    # ### end Alembic commands ###
