"""add_exec_id_to_x402

Revision ID: 5e8c6076824b
Revises: 4a2a4824e77d
Create Date: 2026-08-28 20:18:54.081698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8c6076824b'
down_revision: Union[str, None] = '4a2a4824e77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x402_consumed_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_x402_consumed_payments_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_x402_consumed_payments_execution_id'), ['execution_id'], unique=True)
        batch_op.drop_column('block_number')
        batch_op.drop_column('verified_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x402_consumed_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('block_number', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_x402_consumed_payments_execution_id'))
        batch_op.drop_index(batch_op.f('ix_x402_consumed_payments_endpoint'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('execution_id')

    # ### end Alembic commands ###
