"""Add CapabilityLease

Revision ID: 5eae80473601
Revises: 00e31b0a5c20
Create Date: 2026-08-26 17:04:32.886148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eae80473601'
down_revision: Union[str, None] = '00e31b0a5c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_leases',
    sa.Column('lease_id', sa.String(), nullable=False),
    sa.Column('mount_id', sa.String(), nullable=False),
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('execution_identity', sa.String(), nullable=False),
    sa.Column('subject_spiffe_id', sa.String(), nullable=False),
    sa.Column('executor_spiffe_id', sa.String(), nullable=False),
    sa.Column('biscuit_hash', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_state', sa.String(), nullable=False),
    sa.Column('lease_state_version', sa.Integer(), nullable=False),
    sa.Column('authority_epoch', sa.Integer(), nullable=False),
    sa.Column('revocation_epoch', sa.Integer(), nullable=False),
    sa.Column('delegation_depth', sa.Integer(), nullable=False),
    sa.Column('max_delegation_depth', sa.Integer(), nullable=False),
    sa.Column('allowed_actions', sa.Text(), nullable=False),
    sa.Column('allowed_resources', sa.Text(), nullable=False),
    sa.Column('contextual_bounds', sa.Text(), nullable=False),
    sa.Column('offline_enabled', sa.Boolean(), nullable=False),
    sa.Column('maximum_offline_duration', sa.Integer(), nullable=False),
    sa.Column('offline_budget', sa.Integer(), nullable=False),
    sa.Column('offline_side_effect_limit', sa.Integer(), nullable=False),
    sa.Column('last_known_policy_epoch', sa.Integer(), nullable=False),
    sa.Column('last_known_revocation_epoch', sa.Integer(), nullable=False),
    sa.Column('reconciliation_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lease_id')
    )
    with op.batch_alter_table('capability_leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_leases_biscuit_hash'), ['biscuit_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_leases_capability_id'), ['capability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_leases_execution_identity'), ['execution_identity'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_leases_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_leases_lease_state'), ['lease_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_leases_mount_id'), ['mount_id'], unique=False)

    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.drop_column('resource')

    with op.batch_alter_table('capability_leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_leases_mount_id'))
        batch_op.drop_index(batch_op.f('ix_capability_leases_lease_state'))
        batch_op.drop_index(batch_op.f('ix_capability_leases_expires_at'))
        batch_op.drop_index(batch_op.f('ix_capability_leases_execution_identity'))
        batch_op.drop_index(batch_op.f('ix_capability_leases_capability_id'))
        batch_op.drop_index(batch_op.f('ix_capability_leases_biscuit_hash'))

    op.drop_table('capability_leases')
    # ### end Alembic commands ###
