"""add_license_keys_table

Revision ID: 7386bf0ab803
Revises: bbf243477a0f
Create Date: 2026-06-13 15:56:43.559989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7386bf0ab803'
down_revision: Union[str, None] = 'bbf243477a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=True),
    sa.Column('plan_tier', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('max_activations', sa.Integer(), nullable=True),
    sa.Column('activation_count', sa.Integer(), nullable=True),
    sa.Column('issued_by', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('license_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_license_keys_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_license_keys_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('execution_identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ei_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('tenant_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pgl_certificate_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('subject_json', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('capabilities_json', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('delegation_json', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('budget_json', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('authority_bundle_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('policy_hash', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_execution_identities_pgl_pre_certificate_id'))
        batch_op.drop_index(batch_op.f('ix_execution_identities_workspace_id'))
        batch_op.create_index(batch_op.f('ix_execution_identities_pgl_certificate_id'), ['pgl_certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_identities_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_column('risk_tier')
        batch_op.drop_column('directive')
        batch_op.drop_column('execution_id')
        batch_op.drop_column('scope_json')
        batch_op.drop_column('delegation_depth')
        batch_op.drop_column('hash')
        batch_op.drop_column('pgl_pre_certificate_id')
        batch_op.drop_column('workspace_id')
        batch_op.drop_column('budget_approved_cents')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_approved_cents', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('workspace_id', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('pgl_pre_certificate_id', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('hash', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('delegation_depth', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('scope_json', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('execution_id', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('directive', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('risk_tier', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_execution_identities_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_execution_identities_pgl_certificate_id'))
        batch_op.create_index(batch_op.f('ix_execution_identities_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_identities_pgl_pre_certificate_id'), ['pgl_pre_certificate_id'], unique=False)
        batch_op.drop_column('policy_hash')
        batch_op.drop_column('authority_bundle_hash')
        batch_op.drop_column('budget_json')
        batch_op.drop_column('delegation_json')
        batch_op.drop_column('capabilities_json')
        batch_op.drop_column('subject_json')
        batch_op.drop_column('pgl_certificate_id')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('ei_id')

    with op.batch_alter_table('license_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_keys_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_license_keys_key'))

    op.drop_table('license_keys')
    # ### end Alembic commands ###
