"""Add tenant_provider_credentials with RLS

Revision ID: 9978153219c2
Revises: c4a1f52d1b0e
Create Date: 2026-08-20 11:53:45.663887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9978153219c2'
down_revision: Union[str, None] = 'c4a1f52d1b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_provider_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('credential_profile', sa.String(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('encrypted_secret', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'credential_profile', name='uix_workspace_provider_profile')
    )
    with op.batch_alter_table('tenant_provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_provider_credentials_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_provider_credentials_workspace_id'), ['workspace_id'], unique=False)
        
    # Enable RLS (only for Postgres)
    if op.get_context().dialect.name == "postgresql":
        op.execute("ALTER TABLE tenant_provider_credentials ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE tenant_provider_credentials FORCE ROW LEVEL SECURITY")
        op.execute('''
            CREATE POLICY tenant_isolation
            ON tenant_provider_credentials
            USING (
                workspace_id::text =
                current_setting('app.workspace_id', true)
            )
            WITH CHECK (
                workspace_id::text =
                current_setting('app.workspace_id', true)
            )
        ''')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_provider_keys',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider_name', sa.VARCHAR(), nullable=False),
    sa.Column('api_key_encrypted', sa.VARCHAR(), nullable=True),
    sa.Column('base_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_provider_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_provider_keys_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_provider_keys_provider_name'), ['provider_name'], unique=False)

    with op.batch_alter_table('tenant_provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_provider_credentials_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_provider_credentials_provider'))

    op.drop_table('tenant_provider_credentials')
    # ### end Alembic commands ###
