"""add signed_receipt_cose

Revision ID: a106f10602a5
Revises: 3f5c8bcd93f7
Create Date: 2026-08-26 14:08:57.076110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a106f10602a5'
down_revision: Union[str, None] = '3f5c8bcd93f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signed_receipt_cose', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_action_receipts', schema=None) as batch_op:
        batch_op.drop_column('signed_receipt_cose')

    # ### end Alembic commands ###
