"""create_genomes_and_genome_lineage_tables

Revision ID: bbf243477a0f
Revises: d6229158add7
Create Date: 2026-06-11 12:54:04.325582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf243477a0f'
down_revision: Union[str, None] = 'd6229158add7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genome_lineage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_genome_hash', sa.String(), nullable=False),
    sa.Column('to_genome_hash', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genome_lineage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genome_lineage_from_genome_hash'), ['from_genome_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_genome_lineage_to_genome_hash'), ['to_genome_hash'], unique=False)

    op.create_table('genomes',
    sa.Column('genome_hash', sa.String(), nullable=False),
    sa.Column('genome_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_layer', sa.JSON(), nullable=False),
    sa.Column('prompt_layer', sa.JSON(), nullable=False),
    sa.Column('policy_layer', sa.JSON(), nullable=False),
    sa.Column('watchtower_layer', sa.JSON(), nullable=False),
    sa.Column('task_profile', sa.JSON(), nullable=False),
    sa.Column('model_layer_hash', sa.String(), nullable=False),
    sa.Column('prompt_layer_hash', sa.String(), nullable=False),
    sa.Column('policy_layer_hash', sa.String(), nullable=False),
    sa.Column('watchtower_layer_hash', sa.String(), nullable=False),
    sa.Column('task_profile_hash', sa.String(), nullable=False),
    sa.Column('merkle_proof', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('genome_hash')
    )
    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genomes_genome_id'), ['genome_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genomes_genome_id'))

    op.drop_table('genomes')
    with op.batch_alter_table('genome_lineage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genome_lineage_to_genome_hash'))
        batch_op.drop_index(batch_op.f('ix_genome_lineage_from_genome_hash'))

    op.drop_table('genome_lineage')
    # ### end Alembic commands ###
