"""create_execution_authorizations_table_and_eat_column

Revision ID: d6229158add7
Revises: fdc365c5793c
Create Date: 2026-06-10 19:46:25.710045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6229158add7'
down_revision: Union[str, None] = 'fdc365c5793c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_authorizations',
    sa.Column('eat_id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('directive', sa.String(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('eat_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('eat_id')
    )
    with op.batch_alter_table('execution_authorizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_authorizations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_authorizations_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_authorizations_nonce'), ['nonce'], unique=False)

    with op.batch_alter_table('governed_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eat', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('governed_runs', schema=None) as batch_op:
        batch_op.drop_column('eat')

    with op.batch_alter_table('execution_authorizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_authorizations_nonce'))
        batch_op.drop_index(batch_op.f('ix_execution_authorizations_execution_id'))
        batch_op.drop_index(batch_op.f('ix_execution_authorizations_agent_id'))

    op.drop_table('execution_authorizations')
    # ### end Alembic commands ###
