"""phase1 governance kernel schema

Revision ID: ee84a9b13322
Revises: 
Create Date: 2026-06-08 01:51:42.301559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee84a9b13322'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('previous_log_hash', sa.String(), nullable=True),
    sa.Column('log_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('execution_identities',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('pgl_pre_certificate_id', sa.String(), nullable=False),
    sa.Column('pgl_post_certificate_id', sa.String(), nullable=True),
    sa.Column('directive', sa.String(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('budget_approved_cents', sa.Integer(), nullable=False),
    sa.Column('delegation_depth', sa.Integer(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('identity_json', sa.JSON(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('execution_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_identities_pgl_pre_certificate_id'), ['pgl_pre_certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_identities_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_identities_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('governed_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('delegation_depth', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('governance_decision', sa.String(), nullable=True),
    sa.Column('risk_tier', sa.String(), nullable=True),
    sa.Column('pgl_identity', sa.JSON(), nullable=False),
    sa.Column('seked_state', sa.JSON(), nullable=False),
    sa.Column('v4_decision', sa.JSON(), nullable=False),
    sa.Column('hashes', sa.JSON(), nullable=False),
    sa.Column('approved_budget_cents', sa.Integer(), nullable=False),
    sa.Column('reserve_cents', sa.Integer(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('execution_identity', sa.JSON(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('governed_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governed_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_governed_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pgl_certificates',
    sa.Column('certificate_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('pre_execution_certificate_id', sa.String(), nullable=True),
    sa.Column('post_execution_certificate_id', sa.String(), nullable=True),
    sa.Column('genome_hash', sa.String(), nullable=False),
    sa.Column('constitution_hash', sa.String(), nullable=False),
    sa.Column('plan_hash', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=True),
    sa.Column('output_hash', sa.String(), nullable=True),
    sa.Column('outcome_hash', sa.String(), nullable=True),
    sa.Column('decision_frame_hash', sa.String(), nullable=True),
    sa.Column('governance_decision', sa.String(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('approved_budget_cents', sa.Integer(), nullable=False),
    sa.Column('reserve_cents', sa.Integer(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('persisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    with op.batch_alter_table('pgl_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pgl_certificates_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pgl_certificates_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pgl_ledger_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('certificate_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('previous_event_hash', sa.String(), nullable=True),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('pgl_ledger_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pgl_ledger_events_certificate_id'), ['certificate_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pgl_ledger_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pgl_ledger_events_certificate_id'))

    op.drop_table('pgl_ledger_events')
    with op.batch_alter_table('pgl_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pgl_certificates_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_pgl_certificates_run_id'))

    op.drop_table('pgl_certificates')
    with op.batch_alter_table('governed_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governed_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_governed_runs_tenant_id'))

    op.drop_table('governed_runs')
    with op.batch_alter_table('execution_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_identities_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_execution_identities_run_id'))
        batch_op.drop_index(batch_op.f('ix_execution_identities_pgl_pre_certificate_id'))

    op.drop_table('execution_identities')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_operation_type'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
