"""add_x402_consumed_payments

Revision ID: f33e7a6b27ef
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 00:54:59.991730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33e7a6b27ef'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x402_consumed_payments',
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('amount_usdc', sa.String(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=False),
    sa.Column('block_number', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    with op.batch_alter_table('x402_consumed_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x402_consumed_payments_wallet_address'), ['wallet_address'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x402_consumed_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x402_consumed_payments_wallet_address'))

    op.drop_table('x402_consumed_payments')
    # ### end Alembic commands ###
