"""phase3 kill switch and workspace budget

Revision ID: fdc365c5793c
Revises: ee84a9b13322
Create Date: 2026-06-08 02:07:46.422323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc365c5793c'
down_revision: Union[str, None] = 'ee84a9b13322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switches',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('workspace_budgets',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('balance_cents', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_budgets')
    op.drop_table('kill_switches')
    # ### end Alembic commands ###
