agent {
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"
    server_address = "localhost"
    server_port = "8081"
    socket_path = "/tmp/spire-sockets/workload_api.sock"
    trust_domain = "example.org"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {
        }
    }
    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data"
        }
    }
    WorkloadAttestor "unix" {
        plugin_data {
        }
    }
}
